### ISSUE TITLE
Code - NPC Plant Mutant AI

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#140]
Needs: Activities for idle, patrolling, exploring, chasing, searching, projectile seed-pod attack, touch-damage attack (barbs on skin), die.

**Comment by bastardrodent** [comment]
![plant-mutant](https://cloud.githubusercontent.com/assets/14824120/14540931/881aee98-0255-11e6-94b7-d2d14c3ff5de.gif)
