### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [JosiahJack/Citadel#167]
I was wondering if Linux support was planned.

Thanks!

**Comment by JosiahJack** [comment]
Currently, Mac and Linux support are planned in addition to Windows.  While I currently do not have a Linux PC available, I do have a Ubuntu boot flash drive that I can use to test it.

**Comment by neuromancer** [comment]
There is a large number of potential testers in  [/r/linux_gaming](https://www.reddit.com/r/linux_gaming/). You can just post a link to the alpha build and ask to report bugs here. In fact, they already know Citadel in that subreddit.
