### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by ShalokShalom** [JosiahJack/Citadel#283]
How to install?

**Comment by JosiahJack** [comment]
DISCLAIMER: Citadel is in-progress.  That means features may be broken, missing, or not in a final state of polish.  Also, this means that the game is not in an "installable" state and must be "built" in Unity OR ran inside the Unity editor.  Also, the github version is always updated after I get to a reasonable "stopping point" for adding to the game.  This means Github is missing certain features that are actually closed in the Issues list on here (I'll change this at some point where I don't close bugs for instance until after the commit is done for that bug.)  Continue for your own fun.

1. Download the Github repository.
2. Install Unity 2017.2.0: https://unity3d.com/get-unity/download/archive
3. Extract all into a folder and name of your liking.
4. Open Unity.
5. Click on Open Other or Open Project (the name if the button changes depending on whether it is a fresh install or already installed.)
6. Select the top folder where you extracted the game files.  It must be only one level above the Assets folder, e.g. Citadel-v0.1/Assets.
7. Wait as Unity loads in the project and reimports all assets and auto-compiles the script code (may take an hour for the very first time).
8. Either A. Click the play button at the top of the screen (it's a triangle), or B. In the top menu bar go to File->Build & Run.

**Comment by ShalokShalom** [comment]
You might want to port that into your README
