### ISSUE TITLE
BUG: IndexOutOfRangeException when tossing away a weapon then swapping with hotkey

### ISSUE THREAD

**Issue by Denhonator** [JosiahJack/Citadel#292]
**Describe the bug**
I threw away my extra dartgun and tried to hit the hotkeys to change weapon when the error came up and no weapon was equipped. Hitting the next weapon hotkey again worked and gave me a weapon though. Now I have pipe, dartgun and pistol and I can swap between pipe and dartgun but trying to swap to pistol gives the error every time. I can click to equip any weapon no problem. Picking the dartgun back up got rid of the bug. Throwing away any weapon can cause the bug again. The only case when throwing a weapon that the bug doesn't happen seems to be if I have the bottom weapon equipped and throw that away.

**To Reproduce**
Steps to reproduce:
1. Acquire at least 2 weapons
2. Equip the top weapon in the list
3. Throw away another weapon
4. Use the hotkeys to swap weapons until bug occurs

**Expected behavior**
Able to swap between current weapons after tossing away weapons

**Rig:**
 - OS and version: Windows 10
 - CPU: AMD Ryzen 3700X
 -GPU: GTX 1070

**Comment by JosiahJack** [comment]
Well I thought I already fixed this, ugh.  Guess I only fixed it for the 7th weapon.
