### ISSUE TITLE
BUG: Issue with saving the game

### ISSUE THREAD

**Issue by Denhonator** [JosiahJack/Citadel#293]
**Describe the bug**
I tried to quit to main menu and save. I chose an unused slot and the "- unused -" text overlapped with "Enter name..." later replaced by whatever I was typing. Hitting enter to confirm gave a null reference exception. However, I'm able to still load the game even though the slot is titled "- unused -". However, after this, trying to start a new game or load a file, I first can't control my character until I hit escape 2 times. Also, the world state seems to not load/reset. For example, starting a new game, all the items have already been picked up and enemies are already dead. 

**To Reproduce**
Steps to reproduce:
1. Quit and save, choose a slot, type something and hit enter
2. Load that game (kinda works)
3. Pick up the pipe or any other item in a new game, start a new game and it will be gone

**Expected behavior**
Able to save the game without encountering bugs. Able to load the game or start a new game correctly.

**Screenshots**

**Rig:**
 - OS and version: Windows 10
 - CPU: AMD Ryzen 3700X
 -GPU: GTX 1070

**Comment by JosiahJack** [comment]
Overlapping text fixed.  Technically this should have been its own separate bug.

**Comment by JosiahJack** [comment]
Also fixed escaping from text entry closing the whole save page.

**Comment by JosiahJack** [comment]
Fixed savename charachter limit from 10 to 40.

**Comment by JosiahJack** [comment]
Fixed letting player load empty savefile.

**Comment by JosiahJack** [comment]
Fixed null reference exception during save whenever encountering an NPC who had a null enemy.
Fixed null reference exception whenever encountering an NPC that was missing a HealthManager.

**Comment by JosiahJack** [comment]
Fixed new game resetting everything.

**Comment by JosiahJack** [comment]
Technically these all should have been separate bug reports ;)
