### ISSUE TITLE
BUG: Attack action almost never fires [citadel_v0.91]

### ISSUE THREAD

**Issue by KolyaKorruptis** [JosiahJack/Citadel#295]
**Describe the bug**
I picked up the lead pipe and was able to swing it once. After that it worked only every 30 seconds or so. I tried dropping the pipe but while one pipe was thrown away, I still had one in hand. 
Then I picked up the flechette and couldn't fire it either. Same with the handgrenade.
Maybe I'm missing something obvious.

**To Reproduce**
Steps to reproduce:
1. Pick up pipe
2. Press LMB to swing pipe
3. nothing happens

**Expected behavior**
pipe swings

**Screenshots**

**Rig:**
 - OS and version: Windows 10 (1909)
 - CPU: Intel Core i7-7700 CPU @ 3.60GHz
 -GPU: Nvidia GeForce GTX 1070

**Comment by JosiahJack** [comment]
The viewmodel was being reactivated after being deactivated due to a missing index check.  Fixed.
