### ISSUE TITLE
"TextureArrayIndexAssignment.cs" Build and Run Error...

### ISSUE THREAD

**Issue by dejunai** [JosiahJack/Citadel#315]
"TextureArrayIndexAssignment.cs"

line 24: public static void RevertPrefabPropertyOverrideWithMatchingName(Object ob, string name) {

can only be called if "using UnityEditor"...
UnityEditor only used #if UNITY_EDITOR

necessary change for Build and Run:

@line24:
    #if UNITY_EDITOR
	public static void RevertPrefabPropertyOverrideWithMatchingName(Object ob, string name) {
               SerializedObject serializedObject = new SerializedObject(ob);
               SerializedProperty serializedProperty = serializedObject.FindProperty(name);
               PrefabUtility.RevertPropertyOverride(serializedProperty,InteractionMode.AutomatedAction);
        }
    #endif

Will Build and Run after this change is made.

**Comment by JosiahJack** [comment]
Fixed
