### ISSUE TITLE
Black Void with no world textures

### ISSUE THREAD

**Issue by Tjomo** [JosiahJack/Citadel#317]
I did all the installation correctly, but no matter how I try to run the game, all I get is a black void with no world textures once I start a new game, only the UI. 

Only perpetrator I could assume is that the 2DTextureArrayImport had an error when first opening the project.

**Comment by JosiahJack** [comment]
I've seen where you may need to reimport the 'chunk' material as I believe the Tecture2DArray importer needs the textures imported first before importing the material.  You can right click on it and choose reimport.  It's Assets/Models/Materials/chunk.mat

I might need to check if there's a way to force a certain import order.  It would be nice if Unity named the cached file same as the names I've given them so I could selectively unignore them from git.  Considering just adding the Library folder but not sure that would avoid such things and would double the project size in Github.

**Comment by Pacmikey** [comment]
You mean in Unity right? Where you launch it all you see is a floating NEUROSURGERY? You'll need to have Blender 2.76b installed in the BuildTools folder.

**Comment by JosiahJack** [comment]
Either from testing an old CI build or from not having blender installed.  Considering a non-issue.
