### ISSUE TITLE
3D Model - Keyboard

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#43]
Needs: 3D Model, texturing

Note: Not originally used, see https://tcrf.net/System_Shock (The Cutting Room Floor).  I have elected to use a few of the items that were missing or cut.  These will include so far the keyboard, warecasing, and additional interface demodulator skins/types.  The warecasing and interface demodulator types have already been made.

**Comment by zaklaus** [comment]
Any guidelines for 3D model? Poly count? Art style? I could contribute with some 3D models.

**Comment by JosiahJack** [comment]
Not doing thid until Phase 2
