### ISSUE TITLE
3D Model - NPC Mutant Cyborg

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#54]
Needs: 3D model, texturing, animation

**Comment by bastardrodent** [comment]
![cyborg-mutant](https://cloud.githubusercontent.com/assets/14824120/14655048/8334a246-064e-11e6-86ef-d2cb62db2cdc.gif)

**Comment by bastardrodent** [comment]
![cyborg-mutant](https://cloud.githubusercontent.com/assets/14824120/14708762/f19352ee-079a-11e6-9d47-8b791136c4f2.gif)

**Comment by JosiahJack** [comment]
That looks pretty nice so far.  Can't wait for the claw on the right hand and the hoses on the legs. Keep it up!


________________________________
