### ISSUE TITLE
3D Model - NPC Cyborg Edward Diego

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#56]
Needs: 3D model, texturing, animation

Note: Morphing arms will be tricky.  Might use hooks or a lattice+shape-keys.

**Comment by bastardrodent** [comment]
![cyborg-edward-diego](https://cloud.githubusercontent.com/assets/14824120/14762065/9930c3d8-093f-11e6-99a2-f6a2b34f2abb.gif)
WIP

**Comment by bastardrodent** [comment]
![untitled-2](https://cloud.githubusercontent.com/assets/14824120/14797223/a8d0edd8-0aff-11e6-8557-ee29e1260559.gif)

**Comment by bastardrodent** [comment]
![diego](https://cloud.githubusercontent.com/assets/14824120/14798073/bc804802-0b03-11e6-8a4b-4a278f6d6055.gif)

**Comment by bastardrodent** [comment]
![diego](https://cloud.githubusercontent.com/assets/14824120/14821040/3069b9cc-0b97-11e6-8516-cb37cda1731a.gif)

**Comment by JosiahJack** [comment]
That.  Is.  Awesome!


________________________________
