### ISSUE TITLE
3D Model - NPC Gorilla Tiger Mutant

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#59]
Needs: 3D model, texturing, animation

**Comment by bastardrodent** [comment]
Hello I'm interested in helping out. Is this the kind of stuff you are looking for?
![gorilatiger](https://cloud.githubusercontent.com/assets/14824120/10078518/1048b0e0-62b3-11e5-90b9-b55c704620eb.gif)
It's about 750 tris...

**Comment by JosiahJack** [comment]
Yes!  That looks great!

**Comment by JosiahJack** [comment]
@bastardrodent I'm not sure how to contact you. It appears that Github doesn't have any way to message someone.  Please message me on either www.systemshock.org or http://www.indiedb.com/members/josiahjack
