### ISSUE TITLE
3D Model - NPC Humanoid Mutant

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#61]
Needs: 3D model, texturing, animation

Note: Model started, not completely happy with it yet, needs tweaking before texturing or animation is started.

**Comment by bastardrodent** [comment]
![screen shot 2016-04-14 at 6 37 14 pm](https://cloud.githubusercontent.com/assets/14824120/14545995/33cbb802-0270-11e6-8b1c-2574ad1351ea.png)
WIP

**Comment by bastardrodent** [comment]
![screen shot 2016-04-18 at 3 33 54 pm](https://cloud.githubusercontent.com/assets/14824120/14617129/167c19b4-057b-11e6-8c98-b6ef4612f42d.png)

**Comment by JosiahJack** [comment]
These are awesome!  Keep em coming please.


Update for you:

FYI, doors, switches, elevators, keypads, and elevator keypads are all working now.  Inventory works too.  Current github repository updated with all changes as of 4/16/16.

Next up: Puzzles, Email system, Paper log reading.

On-going: Adding lights to all levels.  Levels lighting done: 1, 2, 3, 4.  Partial: R, 5, 6.

            Adding doors to all levels.  Partial: R, 1, 2, 3, 4, 5, 6.

            Adding objects to all levels.  Partial: 1, 2, 3, 4.


________________________________
