### ISSUE TITLE
3D Model - NPC Virus Mutant

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#67]
Needs: 3D model, texturing, animation

**Comment by bastardrodent** [comment]
![virus-mutant](https://cloud.githubusercontent.com/assets/14824120/14617170/3698af50-057b-11e6-91df-32422933fa70.gif)

**Comment by JosiahJack** [comment]
What version of blender are you using?  I can't seem to open the virus mutant file yet.  Oh well it's not done anyway.  The other files work so far.


________________________________

**Comment by bastardrodent** [comment]
I realized I had copied the wrong file onto the dropbox. It should be fine now, and I am starting to texture it. I am glad you are liking them-I am learning a lot.

________________________________

**Comment by bastardrodent** [comment]
![virus-mutant](https://cloud.githubusercontent.com/assets/14824120/14724938/2fc2b8ce-07e7-11e6-9100-8abeab97f111.gif)

**Comment by JosiahJack** [comment]
Oh that's nasty.  I love it.  Great!


________________________________
