### ISSUE TITLE
3D Model - Skeleton

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#77]
Needs: 3D model, texturing

**Comment by bastardrodent** [comment]
I put together this rigged skeleton.
![](https://media.indiedb.com/images/members/4/3355/3354845/Skeleton_Screen_Shot.png)
The link to download it is here:
https://www.dropbox.com/sh/r13v816rdxs41ny/AAAPwwH61HMth3KFXBBLe9DCa?dl=0

**Comment by JosiahJack** [comment]
Too awesome!  Thank you!!
