### ISSUE TITLE
3D Model - Skull

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#80]
Needs: 3D model, texturing

**Comment by bastardrodent** [comment]
Hi- I put together this skull based on the sprite:
![](https://media.indiedb.com/images/members/4/3355/3354845/skull_Screenshot.png)
You can find the file:
https://www.dropbox.com/sh/5sh3odp7mw9g7v5/AACmUHBUFGWNOJW8OGVJ88bxa?dl=0

**Comment by bastardrodent** [comment]
I also made this severed head, Im not sure were to post the link...
![](https://media.indiedb.com/images/members/4/3355/3354845/Severed_Head_Screen_Shot.png)
https://www.dropbox.com/sh/go72xoicti4g0wk/AACkbw06_ac5WuIKocUL4suSa?dl=0
