### ISSUE TITLE
3D Model - Weapon Magnum

### ISSUE THREAD

**Issue by JosiahJack** [JosiahJack/Citadel#90]
Needs: 3D model, texturing

**Comment by jameswilddev** [comment]
I was hoping to pick this up.  What kind of style did you have in mind for this asset?  I've looked at some of the other weapons which have already been made and it looks like the original spriteart has been amended a little to include textures for sides not in the original spriteart and then modelled around.  Is this what you had in mind?

**Comment by jameswilddev** [comment]
![total](https://cloud.githubusercontent.com/assets/3138458/10149779/9c450a34-6633-11e5-9039-ed1fac93c8df.png)
Rough prototype of how the magnum might look.  Needs topology cleanup beneath barrel, detail on grip.

**Comment by JosiahJack** [comment]
Hello!  Glad you want to help. The style is mostly simple texturing in an (almost) pixel art way. The shape can be based on the UI icon yes, but please take cues from both as to how to make the 2D pop into life as 3D. Thats the fun part. Low poly is key to the style as well, but not so low that it looks blocky. This ain't minecraft.  The final model need not be more than a few hundred tris at most depending on what you need to get the shape right. What is most important is matching the proportions so that it is immediately recognizeable.  That looks pretty sweet so far.  If you want, you can PM me on systemshock.org or over on indiedb.com.

**Comment by JosiahJack** [comment]
@jameswilddev, hey I'm still interested in getting 3D modeling help if you are still offering to help.

**Comment by JosiahJack** [comment]
Hey do you still want to help?



On Mon, Sep 28, 2015 at 12:02 PM -0700, "jameswilddev" <notifications@github.com<mailto:notifications@github.com>> wrote:


I was hoping to pick this up. What kind of style did you have in mind for this asset? I've looked at some of the other weapons which have already been made and it looks like the original spriteart has been amended a little to include textures for sides not in the original spriteart and then modelled around. Is this what you had in mind?

-

**Comment by JosiahJack** [comment]
Model done, needs texturing.
